# Generated by Django 6.0 on 2025-12-15 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='document',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='document',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('in_progress', 'На исполнении'), ('approved', 'Утвержден'), ('rejected', 'Отклонен'), ('completed', 'Исполнен'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('instruction', models.TextField(blank=True, verbose_name='Резолюция/Указание')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('signature', models.CharField(blank=True, max_length=255, verbose_name='Подпись (хэш)')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписи')),
                ('response', models.TextField(blank=True, verbose_name='Ответ исполнителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Назначение документа',
                'verbose_name_plural': 'Назначения документов',
                'ordering': ['-created_at'],
            },
        ),
    ]
