# Generated by Django 6.0 on 2025-12-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('submitted', 'Отправлен на согласование'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('archived', 'Архивирован')], max_length=20, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журналы действий',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(verbose_name='Порядковый номер шага')),
                ('approver_role', models.CharField(help_text='Код роли (например, dept_head, prorector)', max_length=50, verbose_name='Роль согласующего')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Маршрут согласования',
                'verbose_name_plural': 'Маршруты согласования',
                'ordering': ['step_order'],
            },
        ),
    ]
