# Generated by Django 6.0 on 2025-12-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_document_content_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.documentassignment', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись (хэш)'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписи'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('created', 'Создан'), ('registered', 'Зарегистрирован'), ('submitted', 'Отправлен на согласование'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('assigned', 'Назначен исполнитель'), ('accepted', 'Принят к исполнению'), ('completed', 'Исполнен'), ('returned', 'Возвращен на доработку'), ('archived', 'Архивирован'), ('commented', 'Добавлен комментарий')], max_length=20, verbose_name='Действие'),
        ),
    ]
