# Generated by Django 6.0 on 2025-12-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_actionlog_assignment_actionlog_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='action_logs/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
    ]
